/**
 * Table de distances routières (km, aller simple) entre 28 villes françaises.
 * Source : project-doc/distance-ville.csv (matrice routière réelle).
 * 378 paires — générées automatiquement depuis le CSV.
 *
 * Clé : "ville_a|ville_b" normalisée (minuscules, sans accents, tirets→espaces).
 * La table est symétrique — lookup dans les deux sens.
 */

const TABLE: Record<string, number> = {
  "amiens|angers": 369,
  "amiens|biarritz": 862,
  "amiens|bordeaux": 679,
  "amiens|brest": 619,
  "amiens|calais": 159,
  "amiens|cherbourg": 366,
  "amiens|clermont ferrand": 524,
  "amiens|dijon": 417,
  "amiens|grenoble": 674,
  "amiens|le havre": 180,
  "amiens|lille": 113,
  "amiens|lyon": 587,
  "amiens|marseille": 910,
  "amiens|montpellier": 880,
  "amiens|nancy": 358,
  "amiens|nantes": 489,
  "amiens|nice": 1067,
  "amiens|paris": 130,
  "amiens|perpignan": 1043,
  "amiens|reims": 167,
  "amiens|rennes": 411,
  "amiens|rouen": 117,
  "amiens|saint etienne": 604,
  "amiens|strasbourg": 498,
  "amiens|toulouse": 827,
  "amiens|tours": 352,
  "amiens|vichy": 485,
  "angers|biarritz": 518,
  "angers|bordeaux": 335,
  "angers|brest": 371,
  "angers|calais": 494,
  "angers|cherbourg": 290,
  "angers|clermont ferrand": 402,
  "angers|dijon": 498,
  "angers|grenoble": 644,
  "angers|le havre": 297,
  "angers|lille": 503,
  "angers|lyon": 538,
  "angers|marseille": 842,
  "angers|montpellier": 692,
  "angers|nancy": 602,
  "angers|nantes": 90,
  "angers|nice": 999,
  "angers|paris": 303,
  "angers|perpignan": 762,
  "angers|reims": 454,
  "angers|rennes": 126,
  "angers|rouen": 282,
  "angers|saint etienne": 530,
  "angers|strasbourg": 742,
  "angers|toulouse": 552,
  "angers|tours": 106,
  "angers|vichy": 399,
  "biarritz|bordeaux": 183,
  "biarritz|brest": 817,
  "biarritz|calais": 997,
  "biarritz|cherbourg": 808,
  "biarritz|clermont ferrand": 555,
  "biarritz|dijon": 815,
  "biarritz|grenoble": 820,
  "biarritz|le havre": 800,
  "biarritz|lille": 975,
  "biarritz|lyon": 735,
  "biarritz|marseille": 697,
  "biarritz|montpellier": 534,
  "biarritz|nancy": 1001,
  "biarritz|nantes": 512,
  "biarritz|nice": 879,
  "biarritz|paris": 744,
  "biarritz|perpignan": 445,
  "biarritz|reims": 885,
  "biarritz|rennes": 618,
  "biarritz|rouen": 785,
  "biarritz|saint etienne": 705,
  "biarritz|strasbourg": 1141,
  "biarritz|toulouse": 308,
  "biarritz|tours": 510,
  "biarritz|vichy": 609,
  "bordeaux|brest": 634,
  "bordeaux|calais": 814,
  "bordeaux|cherbourg": 625,
  "bordeaux|clermont ferrand": 369,
  "bordeaux|dijon": 632,
  "bordeaux|grenoble": 655,
  "bordeaux|le havre": 617,
  "bordeaux|lille": 792,
  "bordeaux|lyon": 549,
  "bordeaux|marseille": 662,
  "bordeaux|montpellier": 499,
  "bordeaux|nancy": 818,
  "bordeaux|nantes": 329,
  "bordeaux|nice": 844,
  "bordeaux|paris": 561,
  "bordeaux|perpignan": 460,
  "bordeaux|reims": 702,
  "bordeaux|rennes": 435,
  "bordeaux|rouen": 602,
  "bordeaux|saint etienne": 515,
  "bordeaux|strasbourg": 958,
  "bordeaux|toulouse": 250,
  "bordeaux|tours": 327,
  "bordeaux|vichy": 442,
  "brest|calais": 714,
  "brest|cherbourg": 402,
  "brest|clermont ferrand": 752,
  "brest|dijon": 812,
  "brest|grenoble": 996,
  "brest|le havre": 468,
  "brest|lille": 723,
  "brest|lyon": 890,
  "brest|marseille": 1194,
  "brest|montpellier": 1048,
  "brest|nancy": 886,
  "brest|nantes": 305,
  "brest|nice": 1351,
  "brest|paris": 581,
  "brest|perpignan": 1094,
  "brest|reims": 734,
  "brest|rennes": 246,
  "brest|rouen": 502,
  "brest|saint etienne": 900,
  "brest|strasbourg": 1026,
  "brest|toulouse": 884,
  "brest|tours": 456,
  "brest|vichy": 761,
  "calais|cherbourg": 461,
  "calais|clermont ferrand": 672,
  "calais|dijon": 556,
  "calais|grenoble": 840,
  "calais|le havre": 275,
  "calais|lille": 109,
  "calais|lyon": 753,
  "calais|marseille": 1076,
  "calais|montpellier": 1046,
  "calais|nancy": 469,
  "calais|nantes": 584,
  "calais|nice": 1233,
  "calais|paris": 274,
  "calais|perpignan": 1209,
  "calais|reims": 278,
  "calais|rennes": 506,
  "calais|rouen": 212,
  "calais|saint etienne": 800,
  "calais|strasbourg": 609,
  "calais|toulouse": 967,
  "calais|tours": 487,
  "calais|vichy": 633,
  "cherbourg|clermont ferrand": 647,
  "cherbourg|dijon": 661,
  "cherbourg|grenoble": 874,
  "cherbourg|le havre": 215,
  "cherbourg|lille": 470,
  "cherbourg|lyon": 768,
  "cherbourg|marseille": 1072,
  "cherbourg|montpellier": 998,
  "cherbourg|nancy": 635,
  "cherbourg|nantes": 310,
  "cherbourg|nice": 1229,
  "cherbourg|paris": 340,
  "cherbourg|perpignan": 1068,
  "cherbourg|reims": 481,
  "cherbourg|rennes": 204,
  "cherbourg|rouen": 249,
  "cherbourg|saint etienne": 860,
  "cherbourg|strasbourg": 795,
  "cherbourg|toulouse": 858,
  "cherbourg|tours": 351,
  "cherbourg|vichy": 639,
  "clermont ferrand|dijon": 280,
  "clermont ferrand|grenoble": 286,
  "clermont ferrand|le havre": 586,
  "clermont ferrand|lille": 613,
  "clermont ferrand|lyon": 180,
  "clermont ferrand|marseille": 463,
  "clermont ferrand|montpellier": 367,
  "clermont ferrand|nancy": 472,
  "clermont ferrand|nantes": 469,
  "clermont ferrand|nice": 620,
  "clermont ferrand|paris": 425,
  "clermont ferrand|perpignan": 464,
  "clermont ferrand|reims": 463,
  "clermont ferrand|rennes": 507,
  "clermont ferrand|rouen": 498,
  "clermont ferrand|saint etienne": 145,
  "clermont ferrand|strasbourg": 574,
  "clermont ferrand|toulouse": 389,
  "clermont ferrand|tours": 296,
  "clermont ferrand|vichy": 59,
  "dijon|grenoble": 284,
  "dijon|le havre": 542,
  "dijon|lille": 471,
  "dijon|lyon": 197,
  "dijon|marseille": 520,
  "dijon|montpellier": 490,
  "dijon|nancy": 192,
  "dijon|nantes": 588,
  "dijon|nice": 677,
  "dijon|paris": 323,
  "dijon|perpignan": 653,
  "dijon|reims": 278,
  "dijon|rennes": 567,
  "dijon|rouen": 454,
  "dijon|saint etienne": 240,
  "dijon|strasbourg": 309,
  "dijon|toulouse": 664,
  "dijon|tours": 392,
  "dijon|vichy": 220,
  "grenoble|le havre": 776,
  "grenoble|lille": 755,
  "grenoble|lyon": 106,
  "grenoble|marseille": 277,
  "grenoble|montpellier": 286,
  "grenoble|nancy": 476,
  "grenoble|nantes": 713,
  "grenoble|nice": 337,
  "grenoble|paris": 557,
  "grenoble|perpignan": 449,
  "grenoble|reims": 562,
  "grenoble|rennes": 751,
  "grenoble|rouen": 688,
  "grenoble|saint etienne": 140,
  "grenoble|strasbourg": 505,
  "grenoble|toulouse": 535,
  "grenoble|tours": 538,
  "grenoble|vichy": 265,
  "le havre|lille": 284,
  "le havre|lyon": 676,
  "le havre|marseille": 980,
  "le havre|montpellier": 950,
  "le havre|nancy": 511,
  "le havre|nantes": 357,
  "le havre|nice": 1137,
  "le havre|paris": 211,
  "le havre|perpignan": 1062,
  "le havre|reims": 320,
  "le havre|rennes": 269,
  "le havre|rouen": 88,
  "le havre|saint etienne": 710,
  "le havre|strasbourg": 651,
  "le havre|toulouse": 852,
  "le havre|tours": 290,
  "le havre|vichy": 547,
  "lille|lyon": 668,
  "lille|marseille": 991,
  "lille|montpellier": 961,
  "lille|nancy": 384,
  "lille|nantes": 593,
  "lille|nice": 1148,
  "lille|paris": 223,
  "lille|perpignan": 1124,
  "lille|reims": 193,
  "lille|rennes": 515,
  "lille|rouen": 221,
  "lille|saint etienne": 736,
  "lille|strasbourg": 524,
  "lille|toulouse": 940,
  "lille|tours": 465,
  "lille|vichy": 574,
  "lyon|marseille": 323,
  "lyon|montpellier": 293,
  "lyon|nancy": 412,
  "lyon|nantes": 607,
  "lyon|nice": 480,
  "lyon|paris": 470,
  "lyon|perpignan": 456,
  "lyon|reims": 475,
  "lyon|rennes": 645,
  "lyon|rouen": 588,
  "lyon|saint etienne": 57,
  "lyon|strasbourg": 434,
  "lyon|toulouse": 542,
  "lyon|tours": 432,
  "lyon|vichy": 159,
  "marseille|montpellier": 163,
  "marseille|nancy": 712,
  "marseille|nantes": 911,
  "marseille|nice": 197,
  "marseille|paris": 793,
  "marseille|perpignan": 326,
  "marseille|reims": 798,
  "marseille|rennes": 949,
  "marseille|rouen": 892,
  "marseille|saint etienne": 330,
  "marseille|strasbourg": 757,
  "marseille|toulouse": 412,
  "marseille|tours": 736,
  "marseille|vichy": 457,
  "montpellier|nancy": 682,
  "montpellier|nantes": 743,
  "montpellier|nice": 345,
  "montpellier|paris": 763,
  "montpellier|perpignan": 163,
  "montpellier|reims": 768,
  "montpellier|rennes": 818,
  "montpellier|rouen": 862,
  "montpellier|saint etienne": 323,
  "montpellier|strasbourg": 727,
  "montpellier|toulouse": 249,
  "montpellier|tours": 647,
  "montpellier|vichy": 427,
  "nancy|nantes": 692,
  "nancy|nice": 869,
  "nancy|paris": 308,
  "nancy|perpignan": 845,
  "nancy|reims": 191,
  "nancy|rennes": 659,
  "nancy|rouen": 423,
  "nancy|saint etienne": 460,
  "nancy|strasbourg": 140,
  "nancy|toulouse": 856,
  "nancy|tours": 491,
  "nancy|vichy": 412,
  "nantes|nice": 1068,
  "nantes|paris": 393,
  "nantes|perpignan": 789,
  "nantes|reims": 544,
  "nantes|rennes": 106,
  "nantes|rouen": 372,
  "nantes|saint etienne": 607,
  "nantes|strasbourg": 832,
  "nantes|toulouse": 579,
  "nantes|tours": 196,
  "nantes|vichy": 466,
  "nice|paris": 950,
  "nice|perpignan": 508,
  "nice|reims": 955,
  "nice|rennes": 1106,
  "nice|rouen": 1049,
  "nice|saint etienne": 427,
  "nice|strasbourg": 842,
  "nice|toulouse": 594,
  "nice|tours": 893,
  "nice|vichy": 614,
  "paris|perpignan": 926,
  "paris|reims": 155,
  "paris|rennes": 360,
  "paris|rouen": 123,
  "paris|saint etienne": 517,
  "paris|strasbourg": 448,
  "paris|toulouse": 681,
  "paris|tours": 234,
  "paris|vichy": 343,
  "perpignan|reims": 931,
  "perpignan|rennes": 895,
  "perpignan|rouen": 974,
  "perpignan|saint etienne": 481,
  "perpignan|strasbourg": 948,
  "perpignan|toulouse": 210,
  "perpignan|tours": 717,
  "perpignan|vichy": 590,
  "reims|rennes": 511,
  "reims|rouen": 232,
  "reims|saint etienne": 537,
  "reims|strasbourg": 331,
  "reims|toulouse": 806,
  "reims|tours": 375,
  "reims|vichy": 424,
  "rennes|rouen": 294,
  "rennes|saint etienne": 712,
  "rennes|strasbourg": 836,
  "rennes|toulouse": 685,
  "rennes|tours": 211,
  "rennes|vichy": 516,
  "rouen|saint etienne": 640,
  "rouen|strasbourg": 563,
  "rouen|toulouse": 764,
  "rouen|tours": 275,
  "rouen|vichy": 459,
  "saint etienne|strasbourg": 705,
  "saint etienne|toulouse": 545,
  "saint etienne|tours": 472,
  "saint etienne|vichy": 145,
  "strasbourg|toulouse": 976,
  "strasbourg|tours": 631,
  "strasbourg|vichy": 520,
  "toulouse|tours": 507,
  "toulouse|vichy": 443,
  "tours|vichy": 293,
};

// Alias pour les variantes orthographiques courantes
const ALIASES: Record<string, string> = {
  "clermont ferrand":  "clermont ferrand",
  "clermont-ferrand":  "clermont ferrand",
  "clermont fd":       "clermont ferrand",
  "clermont":          "clermont ferrand",
  "saint etienne":     "saint etienne",
  "saint-etienne":     "saint etienne",
  "le havre":          "le havre",
  "st etienne":        "saint etienne",
};

function normaliser(ville: string): string {
  const base = ville
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[-_]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  return ALIASES[base] ?? base;
}

function cle(a: string, b: string): string {
  return [normaliser(a), normaliser(b)].sort().join("|");
}

/**
 * Retourne la distance en km entre deux villes si connue, sinon null.
 */
export function getDistanceVilles(origine: string, destination: string): number | null {
  return TABLE[cle(origine, destination)] ?? null;
}

/**
 * Estime la distance en km. Lookup exact d'abord, fallback 300 km.
 * L'agent doit signaler que c'est une estimation si estime: true.
 */
export function estimerDistance(
  origine: string,
  destination: string
): { km: number; estime: boolean } {
  const connue = getDistanceVilles(origine, destination);
  if (connue !== null) return { km: connue, estime: false };
  return { km: 300, estime: true };
}
